config/routes.rb
Contacttie::Application.routes.draw do
  get "google/index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "welcome#index"
  get "/contacts/gmail/callback" => "google#index"
  resources :contacts
  get 'tags/:tag', to: 'contacts#index', as: :tag
  resources :tags
  

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, presence: true
	
	acts_as_taggable_on :tags
	belongs_to :user
	
	def self.search_for(query)
    	Contact.where("name LIKE :query OR email LIKE :query OR phone_number LIKE :query OR notes LIKE :query", {:query => "%#{query}%"})
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]

  acts_as_tagger
  has_many :contacts

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"],:uid => data["uid"]).first

    unless user
        user = User.create(name: data["name"],
	    		   email: data["email"], :uid => data["uid"],
	    		   password: Devise.friendly_token[0,20]
	    		  )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.google_data"] && session["devise.google_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_contact, :only => [:edit, :update, :show, :destroy]
  
  def index
  	if params[:tag]
      @contacts = Contact.tagged_with(params[:tag])
    else
      @contacts = Contact.all
    end
  end

  def show
  end

  def new
  	@contact = Contact.new
  end

  def edit
  end

   def create
    safe_contact = params.require(:contact).permit(:name, :email, :phone_number, :notes, :tag, :tags, :tag_list)
    @contact = Contact.new safe_contact

    if @contact.save
      redirect_to @contact
    else
      render 'new'
    end
  end

  def update
  	safe_contact = params.require(:contact).permit(:name, :email, :phone_number, :notes, :tag, :tags, :tag_list)

    if @contact.update(safe_contact)
      redirect_to @contact
    else
      render 'edit'
    end
  end

  def destroy
  	@contact.destroy
  	flash[:notice] = "'#{@contact.name}' has been removed from your address book."

  	redirect_to contacts_path
  end



  private

  def load_contact
  	@contact = Contact.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  	@tags = Contact.tag_counts_on(:tags)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def google_oauth2
	    # You need to implement the method below in your model (e.g. app/models/user.rb)
	    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

	    if @user.persisted?
	      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
	      sign_in_and_redirect @user, :event => :authentication
	    else
	      session["devise.google_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

before_action :redirect_if_logged_in, :only => [:index]
  def index
  	@contacts = Contact.all
  end

  private

  def redirect_if_logged_in
    if user_signed_in?
      redirect_to contacts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_error.html.erb
<ul>
  <% @contact.errors.full_messages.each do |msg| %>
    <li><%=msg%></li>
  <% end %>
</ul>

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
  <fieldset>
    <div class="fields">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="fields">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="fields">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div class="fields">
      <%= f.label :notes %>
      <%= f.text_area :notes %>
    </div>
    <div class="field">
      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list %>
      </div>
  </fieldset>
  <%= f.submit %>
<% end %>

app/views/contacts/_list.html.erb
<div><address>
  <% @contacts.each do |contact| %></br>
      <strong>Name:</strong> <%=link_to contact.name, contact_path(contact) %></br>
      <strong>E-mail:</strong> <%=link_to contact.email %></br>
      <strong>Phone Number: </strong><%= contact.phone_number %> </br>
      <strong>Notes: </strong><%= contact.notes %></br>
      	<i class="icon-tags"> </i>Tags: <%= raw contact.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></br>
    </address>
  <% end %>
</div>

app/views/contacts/_search.html.erb
<%= form_tag '/contacts', method: "GET" do %>
  <%= label_tag :query, "Search:" %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search" %>
<% end %>

app/views/contacts/_tags.html.erb
<div id="tag_cloud">
  	<% tag_cloud Contact.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  	<% end %>
 </div>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render :partial => 'error' %>
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<h1>My Contacts</h1>

<% if flash[:notice] %>
  <div class="notice"><%=flash[:notice]%></div>
<% end %>

<%= render :partial => 'search' %>


<button class="btn" type="button"><%= link_to "Add New Contact", new_contact_path(@contact) %></button>
</br><br>

<%= render :partial => 'list' %>

<%= content_for(:sidebar) do %>
  <section class="well">
    <ul class="nav nav-list">
      <li class="nav-header">Tags</li>
      <li><%= link_to contacts_path(@contact) %></li>
  </ul>
<% end %>

app/views/contacts/new.html.erb
<h1>Add a New Contact!</h1>
<%= render :partial => 'form' %>

app/views/contacts/show.html.erb
<i class="icon-chevron-left"> </i><button class="btn" type="button"><%= link_to "Back to All Contacts", contacts_path(@contact) %></button><br>
<br>
<p><strong>Name:</strong> <%= @contact.name %></p>
<p><strong>E-mail:</strong> <%= @contact.email %></p>
<p><strong>Phone Number:</strong> <%= @contact.phone_number %></p>
<p><strong>Notes:</strong> <%= @contact.notes %></p>
<i class="icon-tags"> </i>Tags: <%= raw @contact.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> </p>


	<button class="btn" type="button"><%= link_to "Edit", edit_contact_path(@contact) %></button>

<button class="btn btn-danger" type="button"><%= link_to 'Delete Contact', contact_path(@contact), method: "DELETE", confirm: "Are you sure you want to delete this contact?" %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ContacTie" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Contacttie</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "My Contacts", contacts_path  %></li>
              <li><%= link_to "My Tags", tags_path  %></li>
              <li><%= link_to "Add New Contact", new_contact_path  %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">SEE WHICH CONTACTS ARE TIED TO A TAG:</li>
                <div id="tag_cloud">
                  <% tag_cloud Contact.tag_counts, %w[s m l] do |tag, css_class| %>
                  <%= link_to tag.name, tag_path(tag.name), class: css_class %>
                  <% end %>
                </div>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ContacTie" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "ContacTie", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                  <li><%= link_to "My Contacts", contacts_path  %></li>
                  <li><%= link_to "New Contact", new_contact_path  %></li>
                  <li><%= link_to "Add New Contact", new_contact_path  %>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; ContacTie</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/tags/index.html.erb
<h4>SEE ALL OF YOUR CONTACTS' TAGS BELOW:</h4>

<div id="tag_cloud">
  <% tag_cloud Contact.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<br/>

app/views/welcome/index.html.erb
<section class="hero-unit">
  <h1>Welcome to ContacTie!</h1>

  <br/>

  <div class='action-buttons'>
    <%= link_to "Create a New Contact", new_contact_path, class: 'btn btn-success btn-large' %>
    <%= link_to "See All Contacts", contacts_path, class: 'btn btn-primary btn-large' %>
    <% if user_signed_in? %>
    	<div class='action-buttons'>
    		<%= link_to "Create a New Contact", new_contact_path, class: 'btn btn-success btn-large' %>
    		<%= link_to "See All Contacts", contacts_path, class: 'btn btn-primary btn-large' %>
    		<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
    	</div>
    <% else %>
    	<div class='action-buttons'>
    		<%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-large' %>
    		<%= link_to "Sign in", new_user_session_path, class: 'btn btn-primary btn-large' %>
    		<%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), class: 'btn btn-primary btn-large' %>
    	</div>
    <% end %>
              
</section>